name: PR Maintainer Feedback

on:
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  handle-maintainer-feedback:
    runs-on: ubuntu-latest
    if: ${{ github.event.review || (github.event.comment && github.event.issue.pull_request) }}
    permissions:
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
      REPOSITORY_NAME: ${{ github.event.repository.full_name }}
    steps:
      - name: Check PR details for comments
        if: ${{ github.event.comment && github.event.issue.pull_request }}
        id: check-pr
        shell: bash
        run: |
          BASE_BRANCH=$(gh pr view $PR_NUMBER --repo $REPOSITORY_NAME --json baseRefName --jq '.baseRefName')
          PR_AUTHOR_ASSOCIATION=$(gh api /repos/$REPOSITORY_NAME/issues/$PR_NUMBER --jq '.user.author_association')
          echo "base_branch=$BASE_BRANCH" >> $GITHUB_OUTPUT
          echo "pr_author_association=$PR_AUTHOR_ASSOCIATION" >> $GITHUB_OUTPUT
          
      - name: Handle maintainer feedback on PR reviews
        if: ${{ github.event.review && contains(fromJSON('["MEMBER", "OWNER"]'), github.event.review.author_association) && !contains(fromJSON('["MEMBER", "OWNER"]'), github.event.pull_request.author_association) && github.event.pull_request.base.ref == 'main' }}
        shell: bash
        run: |
          # Remove pending labels and add pending-community-response
          gh pr edit $PR_NUMBER --repo $REPOSITORY_NAME \
            --remove-label "pending-first-review" \
            --remove-label "pending-maintainer-review" \
            --add-label "pending-community-response"
      
      - name: Handle maintainer feedback on PR comments
        if: ${{ github.event.comment && github.event.issue.pull_request && contains(fromJSON('["MEMBER", "OWNER"]'), github.event.comment.author_association) && !contains(fromJSON('["MEMBER", "OWNER"]'), steps.check-pr.outputs.pr_author_association) && steps.check-pr.outputs.base_branch == 'main' }}
        shell: bash
        run: |
          # Remove pending labels and add pending-community-response
          gh pr edit $PR_NUMBER --repo $REPOSITORY_NAME \
            --remove-label "pending-first-review" \
            --remove-label "pending-maintainer-review" \
            --add-label "pending-community-response"
